import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import LocomotiveScrollProvider from "@/app/contexts/LocomotiveScrollProvider/LocomotiveScrollProvider";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["600", "900"], display: "swap" });

export const metadata: Metadata = {
  title: "The Nordeste Face",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
        <LocomotiveScrollProvider>
        <body className={montserrat.className}>
         {children}
        </body>
        </LocomotiveScrollProvider>
    </html>
  );
}
